terraform:
  - terraform/**/*

lambda:
  - lambda/**/*

documentation:
  - '*.md'
  - docs/**/*

security:
  - .github/workflows/*security*
  - .github/workflows/*scan*

ci/cd:
  - .github/workflows/**
